# Generated by Django 3.2.8 on 2022-01-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20220102_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='producto',
            field=models.CharField(choices=[('Hamburguesa', 'Hamburguesa'), ('Producto2', 'Producto2')], default='Hamburguesa', max_length=30),
        ),
    ]
