# Generated by Django 3.2.8 on 2022-01-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='producto',
        ),
    ]
